### ISSUE TITLE
Example no longer works

### ISSUE THREAD

**Issue by szaske** [mongodb/stitch-examples#29]
I looks like the MongoDB libraries have been updated and these libraries no longer work.  The PlateSpace code refers to:  compile 'org.mongodb:stitch:0.1.0-SNAPSHOT'
while the Stitch online pages point to compile 'org.mongodb:stitch:1.0.0-SNAPSHOT'

Now my app has stopped work and gives me an error $geoNear pipeline is not supported.

**Comment by softytantraa** [comment]
Is there any other example code to refer?

**Comment by szaske** [comment]
Unfortunately not.  You can see their response [here](https://github.com/mongodb/stitch-android-sdk/issues/12#issuecomment-341851020)
