### ISSUE TITLE
toArray() vs. asArray() and Extra Parenthesis in Code

### ISSUE THREAD

**Issue by vbuser2004** [mongodb/stitch-examples#83]
This is an issue with the write up.

In the [Basic Blog](https://docs.mongodb.com/stitch/tutorials/build-blog/) write up, the code uses toArray() in the displayComments() function. It should use asArray() (which is correct in the code posted here). 

Also, #82  identified by @JoeKarlsson is still not corrected in the main code.

**Comment by MongoCaleb** [comment]
@vbuser2004 all SDKs and functions have been standardized on toArray() rather than asArray(). #82 is also fixed now.
